// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crqa_rescale_stat
double crqa_rescale_stat(const NumericMatrix& ts1, const NumericMatrix& ts2, int metric_id, int rescale_kind);
RcppExport SEXP _crqa_crqa_rescale_stat(SEXP ts1SEXP, SEXP ts2SEXP, SEXP metric_idSEXP, SEXP rescale_kindSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts1(ts1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts2(ts2SEXP);
    Rcpp::traits::input_parameter< int >::type metric_id(metric_idSEXP);
    Rcpp::traits::input_parameter< int >::type rescale_kind(rescale_kindSEXP);
    rcpp_result_gen = Rcpp::wrap(crqa_rescale_stat(ts1, ts2, metric_id, rescale_kind));
    return rcpp_result_gen;
END_RCPP
}
// crqa_fused_cpp
List crqa_fused_cpp(const NumericMatrix& ts1, const NumericMatrix& ts2, double radius, int metric_id, int tw, int side, int mindiag, int minvert, bool whiteline);
RcppExport SEXP _crqa_crqa_fused_cpp(SEXP ts1SEXP, SEXP ts2SEXP, SEXP radiusSEXP, SEXP metric_idSEXP, SEXP twSEXP, SEXP sideSEXP, SEXP mindiagSEXP, SEXP minvertSEXP, SEXP whitelineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts1(ts1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts2(ts2SEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type metric_id(metric_idSEXP);
    Rcpp::traits::input_parameter< int >::type tw(twSEXP);
    Rcpp::traits::input_parameter< int >::type side(sideSEXP);
    Rcpp::traits::input_parameter< int >::type mindiag(mindiagSEXP);
    Rcpp::traits::input_parameter< int >::type minvert(minvertSEXP);
    Rcpp::traits::input_parameter< bool >::type whiteline(whitelineSEXP);
    rcpp_result_gen = Rcpp::wrap(crqa_fused_cpp(ts1, ts2, radius, metric_id, tw, side, mindiag, minvert, whiteline));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crqa_crqa_rescale_stat", (DL_FUNC) &_crqa_crqa_rescale_stat, 4},
    {"_crqa_crqa_fused_cpp", (DL_FUNC) &_crqa_crqa_fused_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_crqa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
