# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crqa_rescale_stat <- function(ts1, ts2, metric_id, rescale_kind) {
    .Call(`_crqa_crqa_rescale_stat`, ts1, ts2, metric_id, rescale_kind)
}

crqa_fused_cpp <- function(ts1, ts2, radius, metric_id, tw, side, mindiag, minvert, whiteline) {
    .Call(`_crqa_crqa_fused_cpp`, ts1, ts2, radius, metric_id, tw, side, mindiag, minvert, whiteline)
}

